"""
KnowledgeStage — Pipeline 2 orchestrator.

Emits a frozen, machine-readable knowledge layer to disk:

    output/repo_graph.json   nodes + edges (functions, classes, files, imports, calls)
    output/.okf/<module>.json per-module facts (coverage, complexity, git activity, LLM summary)

Design tenet: the knowledge layer is generated by tools *once*, then frozen.
Downstream stages (task generation) query the frozen artifact — never a live
LLM — so results are deterministic.

Steps:
    1. Static AST scan -> raw graph.
    2. Git enrichment  -> commit history per node.
    3. Coverage import -> attach coverage numbers from hygiene stage.
    4. LLM enrichment  -> short per-module summaries (record mode -> fixtures).
    5. Freeze          -> write JSON files.

Phase 0 status: skeleton only.
"""

from __future__ import annotations

from ..common.stage import Stage, StageContext, StageResult


class KnowledgeStage(Stage):
    name = "knowledge"

    def plan(self, ctx: StageContext) -> dict:
        raise NotImplementedError("Phase 2")

    def run(self, ctx: StageContext) -> StageResult:
        raise NotImplementedError("Phase 2")

    def verify(self, ctx: StageContext) -> bool:
        raise NotImplementedError("Phase 2")
